[package]
name = "rust-calculator"
version = "1.0.0"
description = "A simple mathematical epxression parser and evaluator."
authors = ["Lucas Malandrino <lucas.malandrino@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
thiserror = "1.0.20"
